import { chunk_into_3s } from "./array";
import { OBJData } from "./data-structs";
import { download_data } from "./download_file";

export const download_obj = (obj: OBJData) => {
    const final_string = `
# File generated by Josh Yang's Brown CS 2240 project
${obj.vertices.map(v => `v ${v.x} ${v.y} ${v.z}`).join('\n')}
${chunk_into_3s(obj.indices).map(t => `f ${t[0] + 1} ${t[1] + 1} ${t[2] + 1}`).join('\n')}
`;
    download_data('output.obj', final_string);
}